In [57]:
import datascience

In [58]:
list_of_numbers = [1,2,3,4]
array_of_numbers = datascience.make_array([1,2,3,4])
print('list * 3:',list_of_numbers*3)
print('array * 3:',array_of_numbers*3)

list * 3: [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
array * 3: [[ 3  6  9 12]]


In [59]:
array_2d = datascience.make_array([[1,2,3,4],[1,2,3,4]])
print(array_2d*array_of_numbers)

[[[ 1  4  9 16]
  [ 1  4  9 16]]]


In [60]:
array_2d_add = datascience.make_array([[1,1,1,1],[0,1,0,1]])
print (array_2d,'+\n',array_2d_add,'\n=',array_2d+array_2d_add)


[[[1 2 3 4]
  [1 2 3 4]]] +
 [[[1 1 1 1]
  [0 1 0 1]]] 
= [[[2 3 4 5]
  [1 3 3 5]]]


In [61]:
print(array_2d+5)


[[[6 7 8 9]
  [6 7 8 9]]]


In [62]:
print(array_2d)
print(array_2d * datascience.make_array([2,3,4,5]))
      

[[[1 2 3 4]
  [1 2 3 4]]]
[[[ 2  6 12 20]
  [ 2  6 12 20]]]


In [63]:
print(array_2d + datascience.make_array([2,3,4,5]))

[[[3 5 7 9]
  [3 5 7 9]]]


In [66]:
print('pairwise_product')
print('factor1',array_2d)
multiplier = datascience.make_array([[2,4,6,8],[3,6,9,12]])
print('factor2',multiplier)
print('pairwise product',array_2d*multiplier)

pairwise_product
factor1 [[[1 2 3 4]
  [1 2 3 4]]]
factor2 [[[ 2  4  6  8]
  [ 3  6  9 12]]]
pairwise product [[[ 2  8 18 32]
  [ 3 12 27 48]]]


In [ ]:
import numpy as np
tic_tac_toe = datascience.make_array([[1, 0, 0],
  [0,-1,0],
  [0,0,1]])
change_sides = datascience.make_array([[-1,-1,-1],[-1,-1,-1],[-1,-1,-1]])
flip = datascience.make_array([[0,0,1],[0,1,0],[1,0,0]])
print('change sides',change_sides*tic_tac_toe)
print('flip',np.matmul(flip,tic_tac_toe))
print('flip 2',np.matmul(tic_tac_toe,flip))

In [ ]:
matrix1 = datascience.make_array([[1,2,3],[4,5,6],[7,8,9]])
vector1 = datascience.make_array([1,2,3])
print('matrix times vector',matrix1*vector1)

In [77]:
tic_tac_toe_snapshot = datascience.make_array([[1,0,0],[0,-1,-1],[0,0,1]])
print('trade_sides:',-1 * tic_tac_toe_snapshot)
flip = datascience.make_array([[0,0,1],[0,1,0],[1,0,0]])
print('flip horizontally:',np.matmul(flip,tic_tac_toe_snapshot))
print('flip vertically:',np.matmul(tic_tac_toe_snapshot,flip))      

trade_sides: [[[-1  0  0]
  [ 0  1  1]
  [ 0  0 -1]]]
flip horizontally: [[[ 0  0  1]
  [ 0 -1 -1]
  [ 1  0  0]]]
flip vertically: [[[ 0  0  1]
  [-1 -1  0]
  [ 1  0  0]]]
