In [4]:
import datascience as ds
import numpy as np
path_data = '/home/meyers/DataScienceTools/Lecture9_scripts/data/'
minard = ds.Table.read_table(path_data + 'minard.csv')
print(minard)

Longitude | Latitude | City        | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000


In [6]:
print('There are',minard.num_columns,'columns and',minard.num_rows,'rows.')
print('The columns have these labels',minard.labels)

There are 5 columns and 8 rows.
The columns have these labels ('Longitude', 'Latitude', 'City', 'Direction', 'Survivors')


In [8]:
for array in (minard.columns):
    print(array)

print('City column:',minard.column('City'))

[32.  33.2 34.4 37.6 34.3 32.  30.4 26.8]
[54.8 54.9 55.5 55.8 55.2 54.6 54.4 54.3]
['Smolensk' 'Dorogobouge' 'Chjat' 'Moscou' 'Wixma' 'Smolensk' 'Orscha'
 'Moiodexno']
['Advance' 'Advance' 'Advance' 'Advance' 'Retreat' 'Retreat' 'Retreat'
 'Retreat']
[145000 140000 127100 100000  55000  24000  20000  12000]
City column: ['Smolensk' 'Dorogobouge' 'Chjat' 'Moscou' 'Wixma' 'Smolensk' 'Orscha'
 'Moiodexno']


In [9]:
print(minard.relabeled('City','Populous Regions'))

Longitude | Latitude | Populous Regions | Direction | Survivors
32        | 54.8     | Smolensk         | Advance   | 145000
33.2      | 54.9     | Dorogobouge      | Advance   | 140000
34.4      | 55.5     | Chjat            | Advance   | 127100
37.6      | 55.8     | Moscou           | Advance   | 100000
34.3      | 55.2     | Wixma            | Retreat   | 55000
32        | 54.6     | Smolensk         | Retreat   | 24000
30.4      | 54.4     | Orscha           | Retreat   | 20000
26.8      | 54.3     | Moiodexno        | Retreat   | 12000


In [12]:
print('West to East',minard.sort('Longitude'))
print('South to North',minard.sort('Latitude',descending=True))

West to East Longitude | Latitude | City        | Direction | Survivors
26.8      | 54.3     | Moiodexno   | Retreat   | 12000
30.4      | 54.4     | Orscha      | Retreat   | 20000
32        | 54.8     | Smolensk    | Advance   | 145000
32        | 54.6     | Smolensk    | Retreat   | 24000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.3      | 55.2     | Wixma       | Retreat   | 55000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
South to North Longitude | Latitude | City        | Direction | Survivors
37.6      | 55.8     | Moscou      | Advance   | 100000
34.4      | 55.5     | Chjat       | Advance   | 127100
34.3      | 55.2     | Wixma       | Retreat   | 55000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
32        | 54.8     | Smolensk    | Advance   | 145000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     

In [18]:
print('1st 5 rows')
minard.show(5)
print('\n\nSelected row\n\n',minard.take(1))
print('\n\nSelected rows\n\n',minard.take(np.arange(1,6)))

1st 5 rows




Selected row

 Longitude | Latitude | City        | Direction | Survivors
33.2      | 54.9     | Dorogobouge | Advance   | 140000


Selected rows

 Longitude | Latitude | City        | Direction | Survivors
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000


In [25]:
print('All Seleted Column or Columns\n')
print(minard.select('City','Survivors'))
print('\nAll Columns except seleted ones\n')
print(minard.drop('Direction'))
print('\nChoose rows with Column and Value\n')
print(minard.where('City','Wixma'))

All Seleted Column or Columns

City        | Survivors
Smolensk    | 145000
Dorogobouge | 140000
Chjat       | 127100
Moscou      | 100000
Wixma       | 55000
Smolensk    | 24000
Orscha      | 20000
Moiodexno   | 12000

All Columns except seleted ones

Longitude | Latitude | City        | Survivors
32        | 54.8     | Smolensk    | 145000
33.2      | 54.9     | Dorogobouge | 140000
34.4      | 55.5     | Chjat       | 127100
37.6      | 55.8     | Moscou      | 100000
34.3      | 55.2     | Wixma       | 55000
32        | 54.6     | Smolensk    | 24000
30.4      | 54.4     | Orscha      | 20000
26.8      | 54.3     | Moiodexno   | 12000

Choose rows with Column and Value

Longitude | Latitude | City  | Direction | Survivors
34.3      | 55.2     | Wixma | Retreat   | 55000


In [26]:
minard['Direction']

array(['Advance', 'Advance', 'Advance', 'Advance', 'Retreat', 'Retreat',
       'Retreat', 'Retreat'], dtype='<U7')

In [27]:
minard['Direction'][3]

'Advance'